export const themes: ThemeOption[] = [
  {
    label: "기본 테마",
    backgroundColor: "#ffffff",
    textColor: "#000000",
    backgroundImage: "none",
    backgroundSize: "cover",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    useOverlay: false,
  },
  {
    label: "봄꽃 향기",
    backgroundColor: "#e8f6e8",
    textColor: "#2e6b2e",
    backgroundImage: "url('/patterns/spring-flowers.svg')",
    backgroundSize: "100px 100px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    useOverlay: true,
  },
  {
    label: "여름 바다",
    backgroundColor: "#a0e0ff",
    textColor: "#00466f",
    backgroundImage: "url('/patterns/waves.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    useOverlay: true,
  },
  {
    label: "가을 단풍",
    backgroundColor: "#ffecd1",
    textColor: "#4b2e00",
    backgroundImage: "url('/patterns/autumn-leaves.svg')",
    backgroundSize: "150px 150px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    useOverlay: true,
  },
  {
    label: "겨울 눈송이",
    backgroundColor: "#f0f8ff",
    textColor: "#001f3f",
    backgroundImage: "url('/patterns/snowflakes.svg')",
    backgroundSize: "100px 100px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    useOverlay: true,
  },
  {
    label: "은하수 여행",
    backgroundColor: "#0b0d17",
    textColor: "#ffffff",
    backgroundImage: "url('/patterns/galaxy.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useOverlay: false,
  },
  {
    label: "별이 쏟아지는 밤",
    backgroundColor: "#1a1a2e",
    textColor: "#e0e0e0",
    backgroundImage: "url('/patterns/starry-night.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useOverlay: false,
  },
  {
    label: "오로라 우주",
    backgroundColor: "#0f1b2a",
    textColor: "#a8dadc",
    backgroundImage: "url('/patterns/aurora.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useOverlay: false,
  },
  {
    label: "블랙홀의 심연",
    backgroundColor: "#000000",
    textColor: "#ffdd00",
    backgroundImage: "url('/patterns/blackhole.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useOverlay: false,
  },
];
