export const themes: ThemeOption[] = [
  {
    label: "기본 테마",
    backgroundColor: "#ffffff",
    textColor: "#000000",
    backgroundImage: "none",
    backgroundSize: "cover",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
  },
  {
    label: "봄꽃 향기",
    backgroundColor: "#e8f6e8",
    textColor: "#2e6b2e",
    backgroundImage: "url('/patterns/spring-flowers.svg')",
    backgroundSize: "100px 100px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
  },
  {
    label: "여름 바다",
    backgroundColor: "#a0e0ff",
    textColor: "#00466f",
    backgroundImage: "url('/patterns/waves.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
  },
  {
    label: "가을 단풍",
    backgroundColor: "#ffecd1",
    textColor: "#4b2e00",
    backgroundImage: "url('/patterns/autumn-leaves.svg')",
    backgroundSize: "150px 150px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
  },
  {
    label: "겨울 눈송이",
    backgroundColor: "#f0f8ff",
    textColor: "#001f3f",
    backgroundImage: "url('/patterns/snowflakes.svg')",
    backgroundSize: "100px 100px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
  },
];
