// theme-data.ts

export const themes: ThemeOption[] = [
  {
    label: "기본 테마",
    lightBg: "#ffffff",
    lightText: "#000000",
    darkBg: "#1f1f1f",
    darkText: "#ffffff",
    backgroundImage: "none",
    backgroundSize: "cover",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    lightButtonBg: "#e5e5e5",
    lightButtonText: "#000000",
    darkButtonBg: "#2c2c2c",
    darkButtonText: "#ffffff",
  },
  {
    label: "봄꽃 향기",
    lightBg: "#e8f6e8",
    lightText: "#2e6b2e",
    darkBg: "#223022",
    darkText: "#9bc29b",
    backgroundImage: "url('/patterns/spring-flowers.svg')",
    backgroundSize: "100px 100px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    lightButtonBg: "#4caf50",
    lightButtonText: "#ffffff",
    darkButtonBg: "#357a38",
    darkButtonText: "#ffffff",
  },
  {
    label: "여름 바다",
    lightBg: "#a0e0ff",
    lightText: "#00466f",
    darkBg: "#002a4a",
    darkText: "#88bfff",
    backgroundImage: "url('/patterns/waves.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    lightButtonBg: "#0288d1",
    lightButtonText: "#ffffff",
    darkButtonBg: "#026fa1",
    darkButtonText: "#ffffff",
  },
  {
    label: "가을 단풍",
    lightBg: "#ffecd1",
    lightText: "#4b2e00",
    darkBg: "#402b1c",
    darkText: "#d3b289",
    backgroundImage: "url('/patterns/autumn-leaves.svg')",
    backgroundSize: "150px 150px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    lightButtonBg: "#d2691e",
    lightButtonText: "#ffffff",
    darkButtonBg: "#a65418",
    darkButtonText: "#ffffff",
  },
  {
    label: "겨울 눈송이",
    lightBg: "#f0f8ff",
    lightText: "#001f3f",
    darkBg: "#0a1a2b",
    darkText: "#aaccee",
    backgroundImage: "url('/patterns/snowflakes.svg')",
    backgroundSize: "100px 100px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    lightButtonBg: "#5dade2",
    lightButtonText: "#003366",
    darkButtonBg: "#4a8ac4",
    darkButtonText: "#aaccee",
  },
  {
    label: "은하수 여행",
    lightBg: "#0b0d17",
    lightText: "#ffffff",
    darkBg: "#00000d",
    darkText: "#ccccff",
    backgroundImage: "url('/patterns/galaxy.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    lightButtonBg: "#6a0dad",
    lightButtonText: "#ffffff",
    darkButtonBg: "#580b9a",
    darkButtonText: "#ccccff",
  },
  {
    label: "별이 쏟아지는 밤",
    lightBg: "#1a1a2e",
    lightText: "#e0e0e0",
    darkBg: "#0f0f1a",
    darkText: "#bbbbcc",
    backgroundImage: "url('/patterns/starry-night.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    lightButtonBg: "#34495e",
    lightButtonText: "#ffffff",
    darkButtonBg: "#263648",
    darkButtonText: "#bbbbcc",
  },
  {
    label: "오로라 우주",
    lightBg: "#0f1b2a",
    lightText: "#a8dadc",
    darkBg: "#061018",
    darkText: "#c0e8eb",
    backgroundImage: "url('/patterns/aurora.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    lightButtonBg: "#2ecc71",
    lightButtonText: "#061018",
    darkButtonBg: "#27ae60",
    darkButtonText: "#c0e8eb",
  },
  {
    label: "블랙홀의 심연",
    lightBg: "#000000",
    lightText: "#ffdd00",
    darkBg: "#000000",
    darkText: "#ffdd88",
    backgroundImage: "url('/patterns/blackhole.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    lightButtonBg: "#ffdd00",
    lightButtonText: "#000000",
    darkButtonBg: "#e6c600",
    darkButtonText: "#000000",
  },
  {
    label: "열대 바다",
    lightBg: "#00c4cc",
    lightText: "#003439",
    darkBg: "#004d51",
    darkText: "#80d7db",
    backgroundImage: "url('/patterns/tropical-sea.svg')",
    backgroundSize: "150px 150px",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    lightButtonBg: "#008080",
    lightButtonText: "#ffffff",
    darkButtonBg: "#006666",
    darkButtonText: "#80d7db",
  },
  {
    label: "심해 탐험",
    lightBg: "#002b36",
    lightText: "#83a598",
    darkBg: "#001a20",
    darkText: "#a8c3c2",
    backgroundImage: "url('/patterns/deep-sea.svg')",
    backgroundSize: "cover",
    backgroundRepeat: "repeat",
    backgroundPosition: "center",
    lightButtonBg: "#005f6b",
    lightButtonText: "#ffffff",
    darkButtonBg: "#004951",
    darkButtonText: "#a8c3c2",
  },
];
